---

- name: Create phpfpm log is enabled
  ansible.builtin.file:
    path: "{{ log_path }}"
    mode: 0755
    state: directory

- name: Create phpfpm log is enabled
  changed_when: false
  ansible.builtin.file:
    path: "{{ item }}"
    mode: 0644
    state: touch
  with_items:
    - "{{ log_path }}/php-pool-upstream-error.log"
    - "{{ log_path }}/php-ini-error.log"
    - "{{ log_path }}/php-pool-www-error.log"

- name: Transfer pool.d php-fpm configuration
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ php_fpm_dir }}/pool.d/{{ item | basename }}"
    force: true
    mode: 0644
  with_fileglob:
    - ../templates/config/pool.d/*.conf

- name: Transfer mods-available php configuration
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ php_dir }}/mods-available/{{ item | basename }}"
    force: true
    mode: 0644
  with_fileglob:
    - ../templates/config/mods-available/*.ini

- name: Transfer php.ini php-fpm configuration
  ansible.builtin.template:
    src: config/php.ini
    dest: "{{ php_fpm_dir }}/php.ini"
    force: true
    mode: 0644

- name: Copy pecl extensions .ini files
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ php_dir }}/mods-available/{{ item | basename }}"
    force: true
    mode: 0644
  with_fileglob:
    - ../templates/config/mods-available/*.ini

- name: Transfer php.ini apache configuration
  ansible.builtin.template:
    src: config/php.ini
    dest: "{{ php_dir }}/apache2/php.ini"
    force: true
    mode: 0644
  when: is_web_server_is_apache
  notify:
    - restart apache2

- name: Change php-fpm ownership
  ansible.builtin.file:
    path: "{{ php_dir }}"
    state: directory
    owner: root
    group: root
    recurse: true
  changed_when: "False"

- name: Set is default inslled version
  changed_when: false
  ansible.builtin.command:
    cmd: update-alternatives --set php /usr/bin/php{{ php_version }}
  become: true

- name: Set is default inslled version for apache2
  changed_when: false
  ansible.builtin.command:
    cmd: a2enmod php{{ php_version }}
  when: is_web_server_is_apache
  become: true
  notify:
    - restart apache2

- name: Restart php
  changed_when: false
  ansible.builtin.command:
    cmd: /bin/true
  notify:
    - restart php-fpm
