---

- name: Install

  ansible.builtin.import_tasks: install.yml

- name: Composer

  ansible.builtin.import_tasks: composer.yml
  when: state == "present"

- name: Configure

  ansible.builtin.import_tasks: configure.yml
  when: state == "present"
