---
# install php
- name: add php 7 repo
  apt_repository:
    repo: 'ppa:ondrej/php'
    update_cache: true
    validate_certs: false

- name: install php-fpm and packages
  apt:
    name: [
      'php{{ php_version }}-fpm',
      'php{{ php_version }}',
      'php{{ php_version }}-common',
      'php{{ php_version }}-cli',
      'php{{ php_version }}-curl',
      'php{{ php_version }}-gd',
      'php{{ php_version }}-gmp',
      'php{{ php_version }}-imap',
      'php{{ php_version }}-intl',
      'php{{ php_version }}-readline',
      'php{{ php_version }}-opcache',
      'php{{ php_version }}-mysql',
      'php{{ php_version }}-json',
      'php{{ php_version }}-apcu',
      'php-redis',
      'php{{ php_version }}-apcu',
      'php{{ php_version }}-bz2',
      'php{{ php_version }}-bcmath',
      'php{{ php_version }}-mbstring',
      'php{{ php_version }}-soap',
      'php{{ php_version }}-xml',
      'php{{ php_version }}-zip',
      'php{{ php_version }}-dev',
      'php{{ php_version }}-mongodb',
      'php{{ php_version }}-sqlite3',
      'pkg-config',
      'libssl-dev',
      'libsslcommon2-dev',
      'libpcre3-dev',
      'libsasl2-dev'
    ]
    state: present
    update_cache: true
    cache_valid_time: 5400
  register: phpfpm_result
  notify:
    - reload php-fpm

- name: ensure phpfpm log is enabled
  file:
    path: /var/log/php/
    mode: 0755
    state: directory

- name: ensure phpfpm log is enabled
  changed_when: false
  file:
    path: "{{ item }}"
    mode: 0644
    state: touch
  with_items:
    - /var/log/php-pool-upstream.error.log
    - /var/log/php-pool-queue.error.log
    - /var/log/php-ini-error.log
    - /var/log/php-pool-www.error.log

- name: download composer
  get_url:
    url: http://getcomposer.org/installer
    force: true
    dest: /tmp/composer
    mode: 0755

- name: install composer
  command: php /tmp/composer --install-dir=/usr/local/bin creates=/usr/local/bin/composer  # yamllint disable-line rule:line-length

- name: rename composer.phar to composer
  command: mv /usr/local/bin/composer.phar /usr/local/bin/composer creates=/usr/local/bin/composer  # yamllint disable-line rule:line-length

- name: make composer executable
  file:
    path: /usr/local/bin/composer
    mode: a+x
    state: file
