---
## copy php-fpm config  files

- name: transfer pool.d php-fpm configuration
  template:
    src: "{{ item }}"
    dest: "{{ php_fpm_dir }}/pool.d/{{ item | basename }}"
    force: true
  with_fileglob:
    - ../templates/files/pool.d/*.conf

- name: transfer mods-available php configuration
  template:
    src: "{{ item }}"
    dest: "{{ php_dir }}/mods-available/{{ item | basename }}"
    force: true
  with_fileglob:
    - ../templates/files/mods-available/*.ini

- name: transfer php.ini php-fpm configuration
  template:
    src: files/php.ini
    dest: "{{ php_fpm_dir }}/php.ini"
    force: true

- name: transfer php.ini apache configuration
  template:
    src: files/php.ini
    dest: "{{ php_dir }}/apache2/php.ini"
    force: true
  when: is_web_server_is_apache == true
  notify:
    - restart apache2

- name: change php-fpm ownership
  file:
    path: "{{ php_dir }}"
    state: directory
    owner: root
    group: root
    recurse: yes
  changed_when: "False"

- name: restart php
  changed_when: false
  command: /bin/true
  notify:
    - restart php-fpm
