---
## copy php-fpm files

- name: transfer pool.d php-fpm configuration
  template:
    src: "{{ item }}"
    dest: "/etc/php/7.2/fpm/pool.d/{{ item | basename }}"
    force: true
  with_fileglob:
    - ../templates/files/pool.d/*.conf

- name: transfer mods-available php configuration
  template:
    src: "{{ item }}"
    dest: "/etc/php/7.2/mods-available/{{ item | basename }}"
    force: true
  with_fileglob:
    - ../templates/files/mods-available/*.ini

- name: transfer php.ini php-fpm configuration
  template:
    src: files/php.ini
    dest: "/etc/php/7.2/fpm/php.ini"
    force: true

- name: restart php
  changed_when: false
  command: /bin/true
  notify:
    - restart php-fpm
  when:
