---
## install pecl libraries

- name: update pecl channel
  pear:
    name: pecl/update-channels
    state: present


- name: create pecl extensions .ini files
  template:
    src: files/mods-available/mongodb.ini
    dest: "{{ php_dir }}/mods-available/mongodb.ini"
    owner: root
    group: root
    mode: 0755

- name: enable pecl extensions
  changed_when: false
  command: phpenmod  {{ item }}
  with_items:
    - mongodb
