---

- name: Start php-fpm
  ansible.builtin.service:
    name: "php{{ php_version }}-fpm"
    state: started

- name: Reload php-fpm
  ansible.builtin.service:
    name: "php{{ php_version }}-fpm"
    state: reloaded
  when: state == "present"

- name: Restart php-fpm
  ansible.builtin.service:
    name: "php{{ php_version }}-fpm"
    state: restarted

- name: Restart apache2
  ansible.builtin.service:
    name: Apache2
    state: restarted
    enabled: ture
