name: Docker Image CI

on: [push]

jobs:

  build: 
 
    runs-on: paulfantom/ubuntu-molecule
 
    steps:
    - uses: actions/checkout@v1
    - name: installl Molecule
      run: molecule test
      
