name: Docker Image CI

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-18.04
 
    steps:
    - uses: actions/checkout@v1
    - name: installl vim
      run: sudo apt-get install vim
      run: vim --version
