name: Docker Image CI

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-18.04
 
    steps:
    - uses: actions/checkout@v1
    - name: installl Molecule
      run: mkdir molecule && cd molecule && sudo apt-get install python3-venv && source .venv/bin/activate && pip install -U setuptools pip 'molecule' && molecule --version
      
