name: Docker Image CI

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-18.04
 
    steps:
    - uses: actions/checkout@v1
    - name: installl Molecule
      run: docker run --rm -i -v "$(pwd)":/tmp/$(basename "${PWD}"):ro -v /var/run/docker.sock:/var/run/docker.sock  -w /tmp/$(basename "${PWD}") quay.io/ansible/molecule:2.20 molecule test
      
